services:  
  client:
    build:
      context: .
      target: frontend-service
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ./client:/client
    command: ["pnpm", "run", "dev"]
  
  server:
    build:
      context: . 
      target: backend-service 
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - ./server:/server
    environment:
      - MONGO_URI=${MONGO_URI} 
      - PYTHONPATH=/
    command: ["uvicorn", "server.main:app", "--host", "0.0.0.0", "--port", "${BACKEND_PORT:-8000}", "--reload"]
    depends_on:
      - mongodb
  
  mongodb:  
    image: mongo:latest    
    ports:  
      - "${MONGO_PORT:-27017}:27017"   
    volumes:  
      - mongo_data:/data/db

  seed:
    build:
      context: .
      target: backend-service
    volumes:
      - ./server:/server
    environment:
      - MONGO_URI=${MONGO_URI}
    command: ["python", "app/seed.py"]
    depends_on:
      - server
      - mongodb

volumes:  
  mongo_data:
