services:
  - type: web
    name: quiz-backend
    env: python
    region: oregon
    plan: free
    branch: deploy-backend
    rootDir: server  
    buildCommand: pip install -r requirements.txt
    startCommand: "python -m main"

    autoDeploy: true
