services:
  - type: web
    name: quiz-backend
    env: python
    region: oregon
    plan: free
    branch: deploy-backend
    rootDir: server  
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt    
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
