services:
  - type: web
    name: quiz-backend
    env: python
    region: oregon
    plan: free
    branch: deploy-backend
    buildCommand: pip install -r server/requirements.txt
    startCommand: "uvicorn server.main:app --host 0.0.0.0 --port 10000"
    autoDeploy: true
