services:
  - type: web
    name: fastapi-app
    env: python
    buildCommand: |
      cd server && \
      pip install --upgrade pip && \
      pip install pipenv && \
      pipenv install --system --deploy
    startCommand: bash server/start_server_and_celery.sh
    envVars:
      - key: REDIS_URL
        sync: false
      - key: SENDER_EMAIL
        sync: false
      - key: SENDER_PASSWORD
        sync: false
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "587"
      - key: MONGO_URI
        sync: false
      - key: SHARE_URL
        value: https://quiz-generator-2.vercel.app
    plan: free

